name: portfolio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  go_router: ^7.0.0
  grid_point_4: ^1.0.0
  intl: ^0.18.0
  layout: ^1.0.3
  url_launcher: ^6.1.10

dev_dependencies:
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
